### PR TITLE
Various codon scramble improvements

### PR DESCRIPTION
**Pull request by thecodewarrior**
- Switched to an easier to use a custom format for the codon dictionary
- Made codon key clearer
- Added a seeded RNG
- Preserve whitespace and digits in DNA output
- Truncate GC ratio to two decimal digits
- Sort repetitions by descending count
- Make preset buttons that load directly into the codon dictionary

Is the repetition length or repetition count is more important? At the moment I'm sorting by repetition count and then repetition length, but I don't understand genetic engineering, so it may be more useful to sort by length and then count.

### CODE REVIEW

**Comment by thecodewarrior** [comment]
Just updated it to integrate @otdav33's latest changes (02bf184). This largely consisted of fleshing out the preset list to include the ones they added in that commit.

**Comment by the-thought-emporium** [comment]
So I like the new look but have some comments. I really like the codon table area, that looks great. however I don't like that you need to change the seed manually now. Also aminos should always be submitted in fasta format which has no spaces or numbers. It would be good to be able to submit DNA in non fasta format (spaces and numbers) and get an amino sequence in fasta format because getting rid of the numbers and spaces is annoying. I'm going to merge otdac33s new changes, and if you can rework this to fix those details and be compatible I can merge it after.

**Comment by thecodewarrior** [comment]
I'll get on that! I don't have any experience in that field, so I've mostly just been doing what makes sense to me from a general automation point of view.

**Comment by thecodewarrior** [comment]
Would having a button to generate a new seed work? My thought with the seed is that you could make small changes to the aminos and redo the conversion without having wildly different DNA come out the other end. However, that may not really come up in practice, or it may make more sense to splice the changes in on your end as opposed to scrambling the entire sequence again.

**Comment by the-thought-emporium** [comment]
That wouldn't be super helpful honestly. Totally random seeds and being able to just refresh it and watch the GC content and see when it hits a low number is sufficient and how I've been using it.

**Comment by thecodewarrior** [comment]
Cool. It would also be pretty easy to have it refresh it for you. Like you click "start" and it does the calculation repeatedly, saving the lowest GC content as it goes. Basically just click start, wait for the GC content to go low enough, then click stop and use that.

**Comment by the-thought-emporium** [comment]
I mean having two buttons, one that just picks a random seed and gives you the output, and one that picks 30 seeds and gives you the lowest gc content could be interesting. But in both cases no need to display the seeds, just have it work every time you press the button

**Comment by thecodewarrior** [comment]
I removed the seed field entirely, and now there's a "Minimize GC Ratio" button that will do the conversion 100 times and save the lowest GC ratio. Clicking it again without changing the input will continue where it left off, meaning you can click it repeatedly to try and get the ratio even lower.

**Pull request merged**
