### PR TITLE
Psilocybin E-Coli

### PR DESCRIPTION
**Pull request by ZanzyTHEbar**
A small project i've been working on. I really wanted to share this, and update it as it progresses. The current plasmids do function accurately. Between 150ml/L to 1g/L depending on growth medium and mutation. I have used the T7 H10 promoter, and have plans to apply the site-directed mutagenesis to form better libraries.

### CODE REVIEW

**Comment by decadentsoup** [comment]
Would it be beneficial to commit this after extracting it from the ZIP to gain better diff's?

**Comment by ZanzyTHEbar** [comment]
> Would it be beneficial to commit this after extracting it from the ZIP to gain better diff's?

Sure, i question that upon initial upload myself, i just like zip format. So clean. However, i understand. Will unzip and re-commit for review.

**Comment by the-thought-emporium** [comment]
So, this is very neat and I love the biochem, but I don't think I can add it to the repo. I'm all for making whatever constructs you want, but I feel like having a thing that just straight up makes a substance which is illegal in most countries is asking for trouble and could jeopardize the rest of the repo. Thank you very much for the submission though. It's very cool to know that this works

**Comment by ZanzyTHEbar** [comment]
> So, this is very neat and I love the biochem, but I don't think I can add it to the repo. I'm all for making whatever constructs you want, but I feel like having a thing that just straight up makes a substance which is illegal in most countries is asking for trouble and could jeopardize the rest of the repo. Thank you very much for the submission though. It's very cool to know that this works

I understand, apologies for not considering that. I live in Holland - psilocybin is not as frowned upon here, slips my mind sometimes.

**Comment by the-thought-emporium** [comment]
> > So, this is very neat and I love the biochem, but I don't think I can add it to the repo. I'm all for making whatever constructs you want, but I feel like having a thing that just straight up makes a substance which is illegal in most countries is asking for trouble and could jeopardize the rest of the repo. Thank you very much for the submission though. It's very cool to know that this works
> 
> I understand, apologies for not considering that. I live in Holland - psilocybin is not as frowned upon here, slips my mind sometimes.

Oh trust me, I hope it's legality is expanded soon. My home country of canada is toying with that. Once that happens, feel free submit this again. But for now I have to turn this down unfortunately.

**Comment by ZanzyTHEbar** [comment]
> > > So, this is very neat and I love the biochem, but I don't think I can add it to the repo. I'm all for making whatever constructs you want, but I feel like having a thing that just straight up makes a substance which is illegal in most countries is asking for trouble and could jeopardize the rest of the repo. Thank you very much for the submission though. It's very cool to know that this works
> > 
> > 
> > I understand, apologies for not considering that. I live in Holland - psilocybin is not as frowned upon here, slips my mind sometimes.
> 
> Oh trust me, I hope it's legality is expanded soon. My home country of canada is toying with that. Once that happens, feel free submit this again. But for now I have to turn this down unfortunately.

I'll keep that in mind ;) I'll delete the files from my fork and upload the files to my own repo - so as to separate the files from you and your work. Feel free to toy with them, Lot's of possibilities with this one. 

The file is already 9270bp - I am wanting to add a GFP for screening, right now the only selection criteria is AmpR xD - but i don't want to add another 1,000+bp. Do you know of a small Fluorescent Protein variant that's low on the bp?

**Comment by the-thought-emporium** [comment]
Wait have you actually made this yet? or are you gonna synthesize the whole thing?

**Comment by ZanzyTHEbar** [comment]
Ive self-synthesized a few colonies in pseudooperon configuration already, and some in basic operon - and i found the basic operon performed better. So now i am modifying the file to account for the change, and i am going to have the whole thing synthesized this time so i only have to transform into the host. This file is the updated version, I am trying to maximize yield and reduce screening/breeding time.

**Comment by the-thought-emporium** [comment]
then.. why are you doing it in ecoli? Use yeast, then it's food safe. Also choose a yeast backbone that has gfp or something in it already

**Comment by ZanzyTHEbar** [comment]
I am used to working with ecoli, and ecoli use a tryptophan synthase beta subunit inherently. This is the unit i am using to consume serine and convert 4-hydroxyindole into 4-hydroxytryptophan. I wanted to get the biochemical pathway verified before i experimented with inserting the tryptophan synthase sequence into yeast. In theory i can just use 4-hydroxytryptophan as media supplement, and ignore this initial pathway. However, this pathway is more efficient and cost effective.

**Comment by the-thought-emporium** [comment]
Tryptophan synthase is an auxotrophic marker used in some yeast plasmids. The beta carotene plasmid I have uses it. So find a plasmid that has tryp selection, gfp built in, and a nice MCS. Then just add in the other 2-3 genes. Maybe separate them by a p2a linker. Should work well. And no need to supplement

**Comment by ZanzyTHEbar** [comment]
I did not know that! I will look deeper into this. Dank je wel! I've been wanting to move over to yeast, but wanting to also retain the functioning pathway was a blocker.

**Comment by the-thought-emporium** [comment]
good luck! feel free to email me if you've got other questions

**Pull request closed without merging**
